accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('',views.index, name='doctor_list'),
    path('login/',views.login, name='login'),
    path('signup/',views.signup, name='signup'),    
    path('profile/<slug:slug>/',views.doctor_profile,name='doctor_profile'),
    path('myprofile/',views.my_profile,name='profile'),
]

vesseta/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace='accounts')),

]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User # To one-To-one Relation
from django.utils.translation import ugettext_lazy as _ # TO Translations
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.

Gender = (
    ('M','Male'),
    ('F','Female'),
)   

class Profile(models.Model):
    
    Ta5sos = {
    ("جلدية","جلدية"),
    ("اسنان","اسنان"),
    ("نفسي","نفسي"),
    ("اطفال","اطفال حديثي الولادة"),
    ("مخ","مخ واعصاب"),
    ("عظام","عظام"),
    ("نساء","نساء وتوليد"),
    ("انف","انف واذن وحنجرة"),
    ("قلب","قلب واوعية دموية"),
    ("امراض","امراض دم"),
    ("اورام","اورام"),
    ("باطنه","باطنه"),
    ("تخسيس","تخسيس وتغذية"),
    ("اطفال","جراحة اطفال"),
    ("اورام","جراحة اورام"),
    ("اوعيه","جراحة اوعية دموية"),
    ("تجميل","جراحة تجميل"),
    ("سمنه","جراحه سمنة ومناظير"),
}
    user = models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    name = models.CharField(_("الاسم"), max_length=60)
    doctor = models.CharField(_("دكتور :"),choices=Ta5sos, max_length=60)
    who_i = models.CharField(_("من أنا (نبذه) "), max_length=300 ,null=True,blank=True)
    specialist=models.CharField(_("التخصص : "),choices=Ta5sos ,max_length=80)
    address = models.TextField(_("العنوان بالتفصيل "), max_length=150)
    number_phone = models.CharField(_("رقم الهاتف "),max_length=13)
    working_houres = models.IntegerField(_("عدد ساعات العمل "),default=0)
    waiting_time = models.IntegerField(_("مده الانتظار"),default=0,null=True,blank=True)
    services = models.CharField(_("خدمات الدكتور: "), max_length=100,null=True,blank=True)
    price = models.IntegerField(_("سعر الكشف  "), null=True,blank=True)
    gender = models.CharField(_('النوع '),choices=Gender,max_length = 150)
    image = models.ImageField(_("الصورة الشخصية"), upload_to='media/profile/',default='media/profile/default.png')
    createdAt = models.DateTimeField(_('تاريخ البدء'),auto_now_add=False ,default=timezone.now)
    facebook = models.CharField(_("فيسبوك"),null=True, blank=True, max_length=100)
    twitter = models.CharField(_("تويتر"), null=True, blank=True,max_length=100)
    google = models.CharField(_("جوجل"), null=True, blank=True,max_length=100)
    yahoo = models.CharField(_("ايميل"), null=True, blank=True,max_length=100)
    slug = models.SlugField(_("slug"),null=True,blank=True)

    
  
  
    def save(self, *args, **kwargs):    # Slugify
        if not self.slug:
            self.slug = slugify(self.user.username)
    
        super(Profile, self).save(*args, **kwargs) # Call the real save() method 
    
    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields




class UserCreationForm(UserCreationForm):
    username =  forms.CharField(label='الاسم')
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='البريد الالكتروني')
    password=forms.CharField(label='كلمة السر',widget=forms.PasswordInput(),min_length=8)
    password2=forms.CharField(label='تأكيد كلمه السر',widget=forms.PasswordInput(),min_length=8)
    
    class Meta:
        model = User
        fields=('username','first_name','last_name','email','password','password2')
    
    
class Login_Form(forms.ModelForm):
    username = forms.CharField(label='الاسم')
    password = forms.CharField(label="كلمه السر",widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username','password')

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.models import User,auth

import accounts
from .models import Profile
from . forms import Login_Form , UserCreationForm 
from django.contrib.auth import authenticate, login
from django.contrib import messages  
from django.contrib.auth.decorators import login_required

# Create your views here.



def index(request):
    doctors = Profile.objects.all()
    context = {
        'doctors' : doctors
    }
    return render(request,'index.html',context)


def doctor_profile(request,slug):   
    doctor_profile = Profile.objects.get(slug=slug)
    context = { 
        'doctor_profile' : doctor_profile
    }
    return render(request,'doctor_profile.html',context) 

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)      # Check Authentication
        if user is not None:        # يعني لو اليوزر موجود
            auth.login(request,user)
            return redirect ('/')  # Redirect to a success 
    else:
        form = Login_Form()
    context = {
        'form' : form
    }
    return render(request,'login.html',context)
    
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            login(request , user)
            return redirect('/')
    else:
        form = UserCreationForm()
        
    return render(request,'singnup.html',{'form':form})



    
@login_required(login_url='accounts:login')
def my_profile(request):
    return render(request,'myprofile.html')

accounts/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  

<div dir="rtl">
    {% include "search.html" %}
    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    {% for doctor in doctors %}
                                    
                        <div class="col-lg-10 col-md-10" style="height: 16rem;" >
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div >
                                        
                                        {% if doctor.image %}
                                            
                                            <img  src="{{doctor.image.url}}" alt="" width="100" height="100">
                                        
                                        {% endif %} 
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'accounts:doctor_profile' doctor.slug %}"><h5>دكتور {{doctor.name}} </h5></a>
                                        <h6>{{doctor.who_i}}</h6>
                                        
                                        <div class="links_locat">
                                            <div class="location">
                                                <p> <i class="fas fa-briefcase-medical"></i> دكتور <span style="color: blue;">{{doctor.name}}</span> متخصص في <span style="color: blue;">{{doctor.specialist}}</span></p>
                                                <p> <i class="fa fa-map-marker"></i>address : {{doctor.address}}</p>
                                                <p> <i class="fa fa-map-marker"></i> الكشف : <span style="color: blue;">{{doctor.price}}</span> جنية</p>
                                                <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span style="color: blue;">{{doctor.waiting_time}}</span> ساعه</p>
                                                <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span style="color: blue;">{{doctor.working_houres}}</span> ساعه</p>
                                                <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية  :<span style="color: blue;"> {{doctor.number_phone}} </span>  </p>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="boxed-btn3" href="">حجز كشف</a>
                                    </div>

                                    <div class="rating">
                                        <div class="text-warning">
                                            <!-- to make image category for clinic image -->
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            </div>
                                        <div class="rating" >
                                            <h5>تقييم الدكتور</h5>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
</div>
    <!-- featured_candidates_area_start  -->
    <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title text-center mb-40">
                        <h3>المرشحين المميزين</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="candidate_active owl-carousel">
                        <div class="single_candidates text-center">
                            <div class="thumb">
                                <img class="img-circle " src="{% static 'static_file/img/candiateds/2.png'%}" alt="" >
                                
                            </div>
                            <a href="" ><h4 >الاسم</h4></a>
                            <p>  التخصص</p>
                            <div class="best-rating">
                                <div class="text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        
                                </div>
                                <div class="best-rating" >
                                    <h5>تقييم الدكتور</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- featured_candidates_area_end  -->
{% endblock body %}

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<div dir="rtl">

    <div class="container">
        <div class="signup">
        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h4 class="auth-header">تسجيل الدخول</h4>
                <div class="form-group">
                    {{form.username|as_crispy_field}}
                </div>
                <div class="form-group">
                    {{form.password|as_crispy_field}}
                </div>
                <div class="buttons-w  "><button type="submit" class="btn btn-success ml-5">تسجيل</button>
                <button type="submit" class="btn btn-info  ml-5"><a href="">Github</a></button>
    
                <button type="submit" class="btn btn-primary  ml-5"><a href="">facebook</a></button>
            </div>
            </form>
        </div>
        </div>
    </div>
    </div>
    

{% endblock body %}

accounts/templates/search.html
    <!-- Search -->
    <div class="catagory_area ">
        <div class="container " style="margin-top: 10rem">
                    <div class=" single_text">
                        <h2>احجز مع
                            أفضل دكتور في مصر</h3>
                        <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                        <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                        <br>
                    </div>
                    <form  method="GET" action="">
                    <div class="row cat_search" >
        
                        <div class="col-lg-3 col-md-4">
                            <div class="single_input">
                                <input type="text" placeholder="إسم الدكتور" >
                            </div>
                        </div>
        
                        <div class="col-lg-3 col-md-4">
                            <div class="single_input">
                                <select class="wide" >
                                    <option value="" >الموقع</option>
                                    <option value="المنصوره">المنصوره</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="المنوفية">المنوفية</option>
                                    <option value="الدقي">الدقي</option>
                                    <option value="4">Sylet</option>
                                </select>
                            </div>
                        </div>
        
                        <div class="col-lg-3 col-md-4">
                            <div class="single_input">
                                <select class="wide" >
                                    <option value="">التخصص</option>
                                    <option value="جلدية">جلدية</option>
                                    <option value="اسنان">اسنان</option>
                                    <option value="نفسي">نفسي</option>
                                    <option value="اطفال">اطفال حديثي الولادة</option>
                                    <option value="مخ">مخ واعصاب</option>
                                    <option value="عظام">عظام</option>
                                    <option value="نساء">نساء وتوليد</option>
                                    <option value="انف">انف واذن وحنجرة</option>
                                    <option value="قلب">قلب واوعية دموية</option>
                                    <option value="امراض">امراض دم</option>
                                    <option value="اورام">اورام</option>
                                    <option value="باطنه">باطنه</option>
                                    <option value="تخسيس">تخسيس وتغذية</option>
                                    <option value="جاطفال">جراحة اطفال</option>
                                    <option value="جاورام">جراحة اورام</option>
                                    <option value="جاوعيه">جراحة اوعية دموية</option>
                                    <option value="جتجميل">جراحة تجميل</option>
                                    <option value="سمنه">جراحه سمنة ومناظير </option>
                                    </select>
                            </div>
                        </div>
        
                        <div class="col-lg-3 col-md-12">
                            <div class="job_btn">
                                <input type="submit" class="boxed-btn3" value="ابحث هنا">
                            </div>
                        </div>
        
                    </div>
                    </form> 
                </div>
            </div>
            <!-- endsearch -->

accounts/templates/singnup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<div dir="rtl">

    <div class="container">
        <div class="signup">
        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h4 class="auth-header">تسجيل الدخول</h4>
                <div class="form-group">
                    {{form.username|as_crispy_field}}
                </div>
                <div class="form-group">
                    {{form.email|as_crispy_field}}
                </div>
                <div class='row'>
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.first_name|as_crispy_field}}
                        </div>
                    </div>
                    <div class="col-sm-6">                    
                        <div class="form-group">
                            {{form.last_name|as_crispy_field}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.password|as_crispy_field}}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.password2|as_crispy_field}}
                        </div>
                </div>
                </div>
                <div class="buttons-w  "><button type="submit" class="btn btn-success ml-5">تسجيل</button>
                <button type="submit" class="btn btn-info  ml-5"><a href="">Github</a></button>
    
                <button type="submit" class="btn btn-primary  ml-5"><a href="">facebook</a></button>
            </div>
            </form>
        </div>
        </div>
    </div>
    </div>
    

{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'static_file/img/favicon.png'%}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'static_file/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_file/css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'static_file/css/style.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>

<!-- header-start -->
<header>
<div class="header-area ">
    <div id="sticky-header" class="main-header-area">
        <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
            <div class="header_bottom_border">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'static_file/img/logo2.png'%}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="{% url 'accounts:doctor_list' %}">احجز دكتورك</a></li>|
                                    <li><a href="">المقالات</a></li>|
                                    <li><a href="{% url 'accounts:profile' %}">الصفحه الشخصيه </a></li>|
                                    <li><a href="contact.html">اتصل بنا</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">
                          
                        
                        {% if  user.is_authenticated%}
                            
                            <div class="phone_num d-none d-xl-block"></div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" href="">قدم نفسك</a>
                            </div>
                            
                        {% else %}
                            <div class="phone_num d-none d-xl-block">
                                <a class="boxed-btn3" href="{% url 'accounts:login' %}">تسجل الدخول</a>
                            </div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" style="background-color: crimson;" href="">التسجيل</a>
                            </div>
                        {% endif %}   
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</header>
<!-- header-end -->




{% block body %}
  
{% endblock body %}









<!-- footer start -->
<footer class="footer">
    <div class="footer_top">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                    <div class="footer_logo">
                        <a href="#">
                            <img src="{% static 'static_file/img/logo2.png'%}" alt="logo">
                        </a>
                    </div>
                    <p>
                        mohamedelglad2016@gmail.com <br>
                        +201015360019 <br>
                        Menfoia, Egypt
                    </p>
                    <div class="socail_links">
                        <ul>
                            <li>
                                <a href="https://www.facebook.com/">
                                    <i class="ti-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.youtube.com/">
                                    <i class="fa fa-youtube"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                    <h3 class="footer_title">
                        ماذا عنا
                    </h3>
                    <ul>
                        <li><a href="https://google.com">من نحن </a></li>
                        <li><a href="https://google.com"> أسعارنا</a></li>
                        <li><a href="https://google.com">إستفسار</a></li>
                    </ul>
    
                </div>
            </div>
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                    <h3 class="footer_title">
                        الخدمات
                    </h3>
                    <ul>
                        <li><a href="https://google.com">اعمالنا</a></li>
                        <li><a href="https://google.com">شركائنا</a></li>
                        <li><a href="https://google.com">الخصومات والمشاريع</a></li>
                        <li><a href="https://google.com">للإعلان</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-4 col-md-6 col-lg-4">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                    <h3 class="footer_title">
                        Subscribe
                    </h3>
                    <form action="#" class="newsletter_form">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit">Subscribe</button>
                    </form>
                    <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                        luckily.</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
    <div class="container">
        <div class="footer_border"></div>
        <div class="row">
            <div class="col-xl-12">
                <p class="copy_right text-center">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
    </div>
    </footer>
    <!--/ footer end  -->
    
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'static_file/js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'static_file/js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'static_file/js/popper.min.js'%}"></script>
    <script src="{% static 'static_file/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'static_file/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'static_file/js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'static_file/js/ajax-form.js'%}"></script>
    <script src="{% static 'static_file/js/waypoints.min.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'static_file/js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'static_file/js/scrollIt.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.scrollUp.min.js'%}"></script>
    <script src="{% static 'static_file/js/wow.min.js'%}"></script>
    <script src="{% static 'static_file/js/nice-select.min.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.slicknav.min.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'static_file/js/plugins.js'%}"></script>
    <script src="{% static 'static_file/js/gijgo.min.js'%}"></script>
    
    
    
    <!--contact js-->
    <script src="{% static 'static_file/js/contact.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.form.js'%}"></script>
    <script src="{% static 'static_file/js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'static_file/js/mail-script.js'%}"></script>
    
    
    <script src="{% static 'static_file/js/main.js'%}"></script>
    </body>
    
</html>